blog/urls.py
from django.urls import path
from blog import views


app_name='blogs'

urlpatterns = [

    path('',views.Blog_home,name='bloghome'),
    path('<int:abc>',views.Blog_id,name='blogidlink'),

]

thrid/urls.py
from django.contrib import admin
from django.urls import path,include
from portfolio import views
from django.conf.urls.static import static
from django.conf import settings
from blog import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.Home),
    path('blogs/',include('blog.urls'))

]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class blog_model(models.Model):
    title=models.CharField(max_length=(100))
    description=models.CharField(max_length=(100))
    date=models.DateField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

class Project(models.Model):
    title=models.CharField(max_length=(100))
    description=models.CharField(max_length=(100))
    image=models.ImageField(upload_to='portfolio/images/',null='True')
    url=models.URLField(blank='True')

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import blog_model

def Blog_home(request):
    bloger=blog_model.objects.all()
    return render(request, 'blog/blogpage.html', {'bloger':bloger})

def Blog_id(request,abc):
    efg=get_object_or_404(blog_model, pk=abc)
    return render(request, 'blog/selected.html', {'efg':efg})

portfolio/views.py
from django.shortcuts import render
from .models import Project

def Home(request):
    objectdisplay=Project.objects.all()
    return render(request,'portfolio/home.html',{'display':objectdisplay})

blog/templates/blog/blogpage.html
{% extends 'portfolio/base.html' %}

{% block content %}


{% for blog in bloger %}
<h2><a href="{% url 'blogs:blogidlink' blog.id%}">{{blog.title}}</a></h2>
<h4>{{blog.description}}</h4>
{{blog.date}}
<br><br>
{% endfor %}

{% endblock %}

blog/templates/blog/selected.html
{{efg}}

portfolio/templates/portfolio/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Ankit.</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        {% load static %}
      <!-- Just an image -->
      <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="#">

          <img src="{% static 'portfolio/logo.png'%}" width="40" height="30" alt="" loading="lazy" > Think. Create. Innovate.
        </a>
      </nav>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'blogs:bloghome' %}">Blog<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% static 'portfolio/Resume.pdf'%}">Resume</a>
      </li>

    </ul>

  </div>
</nav>

{% block content %} {% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}

{% block content %}
    <div class="text-center"><br>
    <h1>Ankit's Portfolios </h1>
    </div>
    <br>

    {% load static %}

    <img src="{% static "portfolio/raptor.jpeg" %}" class="rounded mx-auto d-block" height=500,width=400>
    <br>
    <a href="{% url 'blogs:bloghome' %}">BlogLink</a>

    {% for data in display %}
    <h4> {{data.title}} </h4>
      {{data.description}}
      <br>
      <img src="{{data.image.url}}" height=300,width=200>
      <br>
        {%if data.url%}
        <a href="{{data.url}}">Link</a>
        {%endif%}
    {%endfor%}

{% endblock %}